apiVersion: v1
kind: ConfigMap
metadata:
  name: db-backup
  namespace: shopmicro
data:
  backup.sh: |
    #!/bin/sh
    export PGPASSWORD=$POSTGRES_PASSWORD
    pg_dump -h postgres -U postgres shopmicro > /backup/backup-$(date +%F-%H-%M).sql
